name: Run tests with pytest
on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.13"
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pytest
                pip install pytest-repeat

            - name: Run tests
              run: pytest